# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/ERTS_Repo/Assignment_2/vivado_2_7/vivado_2_7.srcs/sources_1/bd/system/ip/system_iosc_0_1/system_iosc_0_1.xci
# IP: The module: 'system_iosc_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ERTS_Repo/Assignment_2/vivado_2_7/vivado_2_7.srcs/sources_1/bd/system/ip/system_iosc_0_1/constraints/iosc_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_iosc_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: c:/ERTS_Repo/Assignment_2/vivado_2_7/vivado_2_7.srcs/sources_1/bd/system/ip/system_iosc_0_1/system_iosc_0_1.xci
# IP: The module: 'system_iosc_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ERTS_Repo/Assignment_2/vivado_2_7/vivado_2_7.srcs/sources_1/bd/system/ip/system_iosc_0_1/constraints/iosc_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_iosc_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
