lappend pragmaStatus0 {pragma "UNROLL" source "C:/ERTS_repo/Project/Xilinx_hls/neural/NN.cpp" location "Classifier::RELU/RELU_label6" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus1 {pragma "UNROLL" source "C:/ERTS_repo/Project/Xilinx_hls/neural/NN.cpp" location "Classifier::Classifier/Classifier_label7" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus2 {pragma "UNROLL" source "C:/ERTS_repo/Project/Xilinx_hls/neural/NN.cpp" location "Classifier::nnLayer/nnLayer_label9" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus3 {pragma "INTERFACE" source "C:/ERTS_repo/Project/Xilinx_hls/neural/NN.cpp" location "classify" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'classify' does not exist in any synthesis source file."}
lappend pragmaStatus4 {pragma "INTERFACE" source "C:/ERTS_repo/Project/Xilinx_hls/neural/NN.cpp" location "classify" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'classify' does not exist in any synthesis source file."}
lappend pragmaStatus0 {pragma "UNROLL" source "C:/ERTS_repo/Project/Xilinx_hls/neural/classifier.cpp" location "Classifier::RELU/RELU_label6" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'Classifier::RELU' does not exist in any synthesis source file."}
lappend pragmaStatus1 {pragma "UNROLL" source "C:/ERTS_repo/Project/Xilinx_hls/neural/classifier.cpp" location "Classifier::Classifier/Classifier_label7" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'Classifier::Classifier' does not exist in any synthesis source file."}
lappend pragmaStatus2 {pragma "UNROLL" source "C:/ERTS_repo/Project/Xilinx_hls/neural/classifier.cpp" location "Classifier::nnLayer/nnLayer_label9" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'Classifier::nnLayer' does not exist in any synthesis source file."}
lappend pragmaStatus3 {pragma "INTERFACE" source "C:/ERTS_repo/Project/Xilinx_hls/neural/classifier.cpp" location "classify" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus4 {pragma "INTERFACE" source "C:/ERTS_repo/Project/Xilinx_hls/neural/classifier.cpp" location "classify" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
