// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// NNIO
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x20 : Data signal of out_r
//        bit 7~0 - out_r[7:0] (Read/Write)
//        others  - reserved
// 0x24 : reserved
// 0x10 ~
// 0x1f : Memory 'img' (16 * 8b)
//        Word n : bit [ 7: 0] - img[4n]
//                 bit [15: 8] - img[4n+1]
//                 bit [23:16] - img[4n+2]
//                 bit [31:24] - img[4n+3]
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XCLASSIFY_NNIO_ADDR_AP_CTRL    0x00
#define XCLASSIFY_NNIO_ADDR_GIE        0x04
#define XCLASSIFY_NNIO_ADDR_IER        0x08
#define XCLASSIFY_NNIO_ADDR_ISR        0x0c
#define XCLASSIFY_NNIO_ADDR_OUT_R_DATA 0x20
#define XCLASSIFY_NNIO_BITS_OUT_R_DATA 8
#define XCLASSIFY_NNIO_ADDR_IMG_BASE   0x10
#define XCLASSIFY_NNIO_ADDR_IMG_HIGH   0x1f
#define XCLASSIFY_NNIO_WIDTH_IMG       8
#define XCLASSIFY_NNIO_DEPTH_IMG       16

