// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xclassify.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XClassify_CfgInitialize(XClassify *InstancePtr, XClassify_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Nnio_BaseAddress = ConfigPtr->Nnio_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XClassify_Start(XClassify *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XClassify_ReadReg(InstancePtr->Nnio_BaseAddress, XCLASSIFY_NNIO_ADDR_AP_CTRL) & 0x80;
    XClassify_WriteReg(InstancePtr->Nnio_BaseAddress, XCLASSIFY_NNIO_ADDR_AP_CTRL, Data | 0x01);
}

u32 XClassify_IsDone(XClassify *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XClassify_ReadReg(InstancePtr->Nnio_BaseAddress, XCLASSIFY_NNIO_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XClassify_IsIdle(XClassify *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XClassify_ReadReg(InstancePtr->Nnio_BaseAddress, XCLASSIFY_NNIO_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XClassify_IsReady(XClassify *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XClassify_ReadReg(InstancePtr->Nnio_BaseAddress, XCLASSIFY_NNIO_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XClassify_EnableAutoRestart(XClassify *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XClassify_WriteReg(InstancePtr->Nnio_BaseAddress, XCLASSIFY_NNIO_ADDR_AP_CTRL, 0x80);
}

void XClassify_DisableAutoRestart(XClassify *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XClassify_WriteReg(InstancePtr->Nnio_BaseAddress, XCLASSIFY_NNIO_ADDR_AP_CTRL, 0);
}

u32 XClassify_Get_return(XClassify *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XClassify_ReadReg(InstancePtr->Nnio_BaseAddress, XCLASSIFY_NNIO_ADDR_AP_RETURN);
    return Data;
}
u32 XClassify_Get_img_BaseAddress(XClassify *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Nnio_BaseAddress + XCLASSIFY_NNIO_ADDR_IMG_BASE);
}

u32 XClassify_Get_img_HighAddress(XClassify *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Nnio_BaseAddress + XCLASSIFY_NNIO_ADDR_IMG_HIGH);
}

u32 XClassify_Get_img_TotalBytes(XClassify *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCLASSIFY_NNIO_ADDR_IMG_HIGH - XCLASSIFY_NNIO_ADDR_IMG_BASE + 1);
}

u32 XClassify_Get_img_BitWidth(XClassify *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCLASSIFY_NNIO_WIDTH_IMG;
}

u32 XClassify_Get_img_Depth(XClassify *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCLASSIFY_NNIO_DEPTH_IMG;
}

u32 XClassify_Write_img_Words(XClassify *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCLASSIFY_NNIO_ADDR_IMG_HIGH - XCLASSIFY_NNIO_ADDR_IMG_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Nnio_BaseAddress + XCLASSIFY_NNIO_ADDR_IMG_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XClassify_Read_img_Words(XClassify *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCLASSIFY_NNIO_ADDR_IMG_HIGH - XCLASSIFY_NNIO_ADDR_IMG_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Nnio_BaseAddress + XCLASSIFY_NNIO_ADDR_IMG_BASE + (offset + i)*4);
    }
    return length;
}

u32 XClassify_Write_img_Bytes(XClassify *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCLASSIFY_NNIO_ADDR_IMG_HIGH - XCLASSIFY_NNIO_ADDR_IMG_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Nnio_BaseAddress + XCLASSIFY_NNIO_ADDR_IMG_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XClassify_Read_img_Bytes(XClassify *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCLASSIFY_NNIO_ADDR_IMG_HIGH - XCLASSIFY_NNIO_ADDR_IMG_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Nnio_BaseAddress + XCLASSIFY_NNIO_ADDR_IMG_BASE + offset + i);
    }
    return length;
}

void XClassify_InterruptGlobalEnable(XClassify *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XClassify_WriteReg(InstancePtr->Nnio_BaseAddress, XCLASSIFY_NNIO_ADDR_GIE, 1);
}

void XClassify_InterruptGlobalDisable(XClassify *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XClassify_WriteReg(InstancePtr->Nnio_BaseAddress, XCLASSIFY_NNIO_ADDR_GIE, 0);
}

void XClassify_InterruptEnable(XClassify *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XClassify_ReadReg(InstancePtr->Nnio_BaseAddress, XCLASSIFY_NNIO_ADDR_IER);
    XClassify_WriteReg(InstancePtr->Nnio_BaseAddress, XCLASSIFY_NNIO_ADDR_IER, Register | Mask);
}

void XClassify_InterruptDisable(XClassify *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XClassify_ReadReg(InstancePtr->Nnio_BaseAddress, XCLASSIFY_NNIO_ADDR_IER);
    XClassify_WriteReg(InstancePtr->Nnio_BaseAddress, XCLASSIFY_NNIO_ADDR_IER, Register & (~Mask));
}

void XClassify_InterruptClear(XClassify *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XClassify_WriteReg(InstancePtr->Nnio_BaseAddress, XCLASSIFY_NNIO_ADDR_ISR, Mask);
}

u32 XClassify_InterruptGetEnabled(XClassify *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XClassify_ReadReg(InstancePtr->Nnio_BaseAddress, XCLASSIFY_NNIO_ADDR_IER);
}

u32 XClassify_InterruptGetStatus(XClassify *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XClassify_ReadReg(InstancePtr->Nnio_BaseAddress, XCLASSIFY_NNIO_ADDR_ISR);
}

