# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/ERTS_repo/Project/Xilinx/ML_MNIST/ML_MNIST.srcs/sources_1/bd/system/ip/system_classify_0_1/system_classify_0_1.xci
# IP: The module: 'system_classify_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ERTS_repo/Project/Xilinx/ML_MNIST/ML_MNIST.srcs/sources_1/bd/system/ip/system_classify_0_1/constraints/classify_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_classify_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/ERTS_repo/Project/Xilinx/ML_MNIST/ML_MNIST.srcs/sources_1/bd/system/ip/system_classify_0_1/system_classify_0_1.xci
# IP: The module: 'system_classify_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ERTS_repo/Project/Xilinx/ML_MNIST/ML_MNIST.srcs/sources_1/bd/system/ip/system_classify_0_1/constraints/classify_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_classify_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
